export const actionType = {
  OPEN_SIDBAR: "OPEN_SIDBAR",
  CLOSE_SIDBAR: "CLOSE_SIDBAR",
  GET_BLOGS_BEGIN: "GET_BLOGS_BEGIN",
  GET_BLOGS_SUCCESS: "GET_BLOGS_SUCCESS",
  GET_BLOGS_ERROR: "GET_BLOGS_ERROR",
  GET_SINGLE_BLOG_BEGIN: "GET_SINGLE_BLOG_BEGIN",
  GET_SINGLE_BLOG_SUCCESS: "GET_SINGLE_BLOG_SUCCESS",
  GET_SINGLE_BLOG_ERROR: "GET_SINGLE_BLOG_ERROR",
  GET_SINGLE_USER_BEGIN: "GET_SINGLE_USER_BEGIN",
  GET_SINGLE_USER_SUCCESS: "GET_SINGLE_USER_SUCCESS",
  GET_SINGLE_USER_ERROR: "GET_SINGLE_USER_ERROR",
  GET_COMMENTS_BY_POST_BEGIN: "GET_COMMENTS_BY_POST_BEGIN",
  GET_COMMENTS_BY_POST_SUCCESS: "GET_COMMENTS_BY_POST_SUCCESS",
  GET_COMMENTS_BY_POST_ERROR: "GET_COMMENTS_BY_POST_ERROR",
  SET_PAGE_COUNT: "SET_PAGE_COUNT",
  GET_BLOG_BY_SEARCHTERM_BEGIN: "GET_BLOG_BY_SEARCHTERM_BEGIN",
  GET_BLOG_BY_SEARCHTERM_SUCCESS: "GET_BLOG_BY_SEARCHTERM_SUCCESS",
  GET_BLOG_BY_SEARCHTERM_ERROR: "GET_BLOG_BY_SEARCHTERM_ERROR",
  SET_SEARCH_TERM: "SET_SEARCH_TERM",
};

export const apiUrl = {
  BLOG_URL: "posts",
  USER_URL: "users",
  COMMENT_BY_POST_URL: "comments/post",
  SEARCH_URL: "posts/search?q=",
}
